
import { Inter } from "next/font/google";
import Scroll from "@/components/Scroll";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "horizontal-page-scroll",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Scroll>
          {children}
         </Scroll>
      </body>
    </html>
  );
}
